services:
  server:
    command: --debug --dbaddr db --dbuser pokerogue --dbpass pokerogue --dbname pokeroguedb --gameurl http://localhost:8000 --callbackurl http://localhost:8001 
    image: ghcr.io/pagefaultgames/rogueserver:master
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
    ports:
      - "8001:8001"

  db:
    image: mariadb:11
    container_name: pokerogue-db-local
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: adminSmashville
      MYSQL_DATABASE: pokeroguedb
      MYSQL_USER: pokerogueSV
      MYSQL_PASSWORD: pokerogueSV
    ports:
      - "3306:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
